# Generated by Django 3.1.7 on 2021-05-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapiprojectapp', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('rating', models.CharField(choices=[('excellent', 1), ('average', 0), ('bad', -1)], default='average', max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='picture/')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['add_date'],
            },
        ),
    ]
